### PR TITLE
Milestone 3 - Friendship v2: Improve Performance of Friendship

### PR DESCRIPTION
**Pull request by anewman15**
In this PR,

I improved the Friendship feature by making the association of Friendship model with User more robust so that we can get all the data we need from the database with only one query, thus improving query performance. Whenever a user confirms an incoming friend request, it creates a reverse Friendship entry with `:confirmed` column set to `true`. This basically means querying only once when we need a list of a user's friends which reduces the performance of the query.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @anewman15 
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] when friendship is confirmed, an additional row with reversed user-friend pair is created. See below
```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
`````
- [x] Now we can find user friends only by user_id in friendships table
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```
- [x] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
- [x] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)
```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
- [x] in order to get all posts written by user on their friends, students can use simple method in User model (in order to NOT do it with Enumerables)
```ruby
# User model

def friends_and_own_posts
  Post.where(user: (self.friends + self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by anewman15** [comment]
Hi @rOluochKe,

1. I have the first feature implemented with the `Friendships#update` action - along with a `create_reverse_confirmed` callback for `after_update` hook.

2-4 . All these features are already implemented, with just different names of the associations.

5. I don't see any use case for this method. Neither it is a part of the specification. Please clarify if I'm wrong.

**Comment by rOluochKe** [comment]
> Hi @rOluochKe,
> 
> 1. I have the first feature implemented with the `Friendships#update` action - along with a `create_reverse_confirmed` callback for `after_update` hook.
> 
> 2-4 . All these features are already implemented, with just different names of the associations.
> 
> 1. I don't see any use case for this method. Neither it is a part of the specification. Please clarify if I'm wrong.

The difference is how you query the database?

**Review by rOluochKe — APPROVED** [review]
### You got it right, well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
