### PR TITLE
Milestone 1 - Create Data Architecture Diagram

### PR DESCRIPTION
**Pull request by anewman15**
In this PR, I created the ERD for Stay In Touch app that involves a user sending friendship request to another user, who can accept or reject it. Also, a user can create a post which can be commented on and liked by all users. All relationships are shown in the diagram using Primary Key and Foreign Keys. Data types of each field is also specified

### CODE REVIEW

**Review by SafaErden — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️

**Hi @anewman15 , your project is awesome. 👐 However, we need a little fix before we can proceed. Kindly find comments below ⤵**
##

**REQUIRED CHANGES**

- [ ] User table should have `image_link` column, please kindly add it.

##

**SUMMARY**

As I mentioned above, your project is almost done.👍

##

*Kindly make the changes and submit another code review when you are ready*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/) 🗨️

Happy coding_ 👨‍💻 

**Safa ERDEN**

**Comment by anewman15** [comment]
Thanks @SafaErden, I've made the asked change

**Review by MarioDena — APPROVED** [review]
Hello Great work implementing the requested changes.

**Review by MarioDena — APPROVED** [review]
# Project approved 🟢 

Cheers!

Code Review by Mario Enrique Delgado Naranjo

**Pull request merged**
